[build-system]
requires = [
    "setuptools >= 45",
    "setuptools_scm[toml]>=6.2",
    "Cython > 3.0.0",
    "numpy > 2.0.0"
    ]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "neural_admixture/_version.py"
fallback_version = "0.1.0"
